### ISSUE TITLE
关于无法爬取页面内容的修复办法

### ISSUE THREAD

**Issue by hspmanbu** [gxtrobot/bustag#112]
研究了好几天，这个古老的项目终于又可以正常使用了，思路就是使用request全面替代aspider，需要设置一个看上去是正常浏览器的header（并不需要cookie登录），修改schedule.py 、bus _spider.py 、parser.py 三个文件，注意meta中的url以及tag_list中的tag_link都需要去除root_path
缺点就是爬取速度稍微慢了一些

**Comment by lihaoze123** [comment]
具体操作能麻烦指点一下吗

**Comment by Banxiaxiala** [comment]
大佬方便放一个源么

**Comment by aiastia** [comment]
修好了（应该） 重写了 爬虫和图片部分， 
改用api 

```
version: '3.8'

services:
  javbus-api:
    image: ovnrain/javbus-api
    container_name: javbus-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    # 如果需要认证，取消注释以下环境变量
    # environment:
    #   - JAVBUS_API_TOKEN=your_token_here

  bustag:
    image: aiastia/bustag:test
    container_name: bustag
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - JAVBUS_API_URL=http://javbus-api:3000
      # - JAVBUS_AUTH_TOKEN=your_token_here
    volumes:
      - ./data:/app/data
    depends_on:
      - javbus-api
```
